# Generated by Django 6.0.3 on 2026-04-06 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TechstackBackend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='TechstackDatabases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='TechstackFrontend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='TechstackTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('svg_icon', models.TextField()),
                ('backend', models.ManyToManyField(related_name='back_projects', to='app.techstackbackend')),
                ('database', models.ManyToManyField(related_name='db_projects', to='app.techstackdatabases')),
                ('frontend', models.ManyToManyField(related_name='front_projects', to='app.techstackfrontend')),
                ('tools', models.ManyToManyField(related_name='tool_projects', to='app.techstacktools')),
            ],
        ),
    ]
